# Generated by Django 5.2.10 on 2026-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=200,
                unique=True,
                verbose_name="URL标识",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="URL标识",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="URL标识",
            ),
        ),
    ]
